sudo: false

language: go

go:
  - '1.12.x'

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - curl -LO https://github.com/lunarway/shuttle/releases/download/$(curl -Lso /dev/null -w %{url_effective} https://github.com/lunarway/shuttle/releases/latest | grep -o '[^/]*$')/shuttle-linux-amd64
  - chmod +x shuttle-linux-amd64
  - sudo mv shuttle-linux-amd64 /usr/local/bin/shuttle


jobs:
  include:
    - stage: build
      script:
        - make build
